package com.viettel.hibernatetest;
// Generated Jun 21, 2017 7:33:29 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NguyendungPersons generated by hbm2java
 */

@Entity
@Table(name = "NGUYENDUNG_PERSONS")
public class NguyendungPersons  implements java.io.Serializable {


     private BigDecimal personId;
     private BigDecimal age;
     private String lastName;
     private String firstName;
     private String address;
     private String city;
     private String email;

    public NguyendungPersons() {
    }

	
    public NguyendungPersons(BigDecimal personId) {
        this.personId = personId;
    }
    
    
    public NguyendungPersons(BigDecimal personId, BigDecimal age, String lastName, String firstName, String address, String city, String email) {
       this.personId = personId;
       this.age = age;
       this.lastName = lastName;
       this.firstName = firstName;
       this.address = address;
       this.city = city;
       this.email = email;
    }
   
//    @SequenceGenerator(name = "generator", sequenceName = "NGUYENDUNG_PERSON_SEQ", allocationSize = 1)
    @Id
//    @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "PERSON_ID", unique = true, nullable = false)
    public BigDecimal getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(BigDecimal personId) {
        this.personId = personId;
    }
    
    @Column (name= "AGE")
    public BigDecimal getAge() {
        return this.age;
    }
    
    public void setAge(BigDecimal age) {
        this.age = age;
    }
    
    @Column (name= "LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    @Column (name= "FIRST_NAME")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    @Column (name= "ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column (name= "CITY")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column (name= "EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Override
    public String toString(){
        return personId+ " - "+ firstName;
    }
    
    @Override
    public boolean equals(Object obj) {
      if (this == obj)
        return true;
      if (obj == null)
        return false;
      if (!(obj instanceof NguyendungPersons))
        return false;
      NguyendungPersons other = (NguyendungPersons) obj;
      return Objects.equals(this.personId, other.personId);
    }
}


